In [1]:
import numpy as np

In [2]:
my_list = [1,2,3]

In [3]:
type(my_list)

list

In [8]:
my_arr = np.array(my_list)

In [5]:
my_list

[1, 2, 3]

In [10]:
my_arr

array([1, 2, 3])

In [11]:
type(my_arr)

numpy.ndarray

In [12]:
my_matrix = [[1,2,3], [4,5,6], [7,8,9]]

In [13]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [14]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
np.arange(0, 101, 20)

array([  0,  20,  40,  60,  80, 100])

DATA SET REEL

In [19]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

ces 0 sont en fet des nbr decimaux et a virgule


y([0., 0., 0., 0

In [21]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
np.zeros((2, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [23]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [24]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

Function  pour creer directement un tableau NumPy

def linspace(start, stop, num = 50, endpoint = True, retstep = False, dtype = None, axis = 0)

In [27]:
np.linspace(0, 10, 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [28]:
len(np.linspace(0, 10, 11))

11

matrice d'identité est toujours carée

In [30]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Créer des distributions de données aleatoires

rand(d0, d1, ..., dn)

In [34]:
np.random.rand(5, 2)

array([[0.98263295, 0.60732827],
       [0.98074312, 0.21852161],
       [0.78880818, 0.64329145],
       [0.33319178, 0.89824182],
       [0.80732851, 0.04368519]])

In [35]:
np.random.randn(5,2)

array([[ 1.29098041,  0.76320864],
       [ 0.25279315, -0.46484492],
       [-0.10691428, -0.61767427],
       [-0.76786118,  0.00837334],
       [-0.74834956,  0.2588749 ]])

In [36]:
np.random.randint(0, 101, (4, 5))

array([[65, 41, 88,  2, 46],
       [36, 44,  9, 87, 84],
       [66,  3, 23, 28, 69],
       [48, 75, 52,  3,  9]])

In [37]:
np.random.randint(0, 101, 10)

array([23, 42,  7, 70, 12, 34, 14, 47, 60, 51])

In [42]:
np.random.seed(101)
np.random.rand(4)

array([0.51639863, 0.57066759, 0.02847423, 0.17152166])

In [43]:
np.random.rand(4)

array([0.68527698, 0.83389686, 0.30696622, 0.89361308])

In [44]:
np.random.rand(4)

array([0.72154386, 0.18993895, 0.55422759, 0.35213195])

In [45]:
arr = np.arange(0, 25)

In [46]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [47]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [48]:
ranarr = np.random.randint(0, 101,10)

In [51]:
ranarr

array([49, 83,  8, 29, 59, 34, 44, 72, 19, 10])

In [52]:
ranarr.max()

83

In [53]:
ranarr.min()

8

In [54]:
ranarr.argmax()

1

In [55]:
ranarr.argmin()

2

In [56]:
ranarr.dtype

dtype('int64')

In [57]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [58]:
arr.shape

(25,)

In [62]:
arr = arr.reshape(5, 5)

In [63]:
arr.shape

(5, 5)